### ISSUE TITLE
http://datapackagist.okfnlabs.org/ is down

### ISSUE THREAD

**Issue by Stephen-Gates** [frictionlessdata/datapackagist#225]
I can't reach http://datapackagist.okfnlabs.org/ is there a problem?

Also not working at http://datapackagist.openknowledge.io what's the correct URL?

**Comment by Stephen-Gates** [comment]
up now

**Comment by Stephen-Gates** [comment]
Closed to quickly http://datapackagist.openknowledge.io doesn't appear to be operational.

Also worth changing references to http://datapackagist.okfnlabs.org/  to http://datapackagist.openknowledge.io and doing a redirect

**Comment by akariv** [comment]
Should be working now.
